adapter:
  consumer:
    mode: batch                    # batch | record
    topic: ${CONSUMER_TOPIC:input-topic}
    group-id: ${CONSUMER_GROUP:orchestrator-adapter-group}
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    max-poll-records: 500
    poll-timeout-ms: 3000
    concurrency: 1
  retry:
    max-attempts: 3
  error:
    strategy: db                   # db | kafka | hybrid
  dlt:
    enabled: false                 # Set to true to enable DLT functionality
    retryable-topic: ${DLT_RETRY_TOPIC:my-retry-dlt}
    non-retryable-topic: ${DLT_NONRETRY_TOPIC:my-nonretry-dlt}
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  db:
    enabled: true
    circuit-breaker: true
    bulk-size: 100
    timeout-ms: 5000

# Kafka Configuration
spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      enable-idempotence: true
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      group-id: ${CONSUMER_GROUP:orchestrator-adapter-group}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
  datasource:
    url: ${DB_URL:jdbc:h2:mem:adapter_db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Target producer configuration
target:
  kafka:
    topic: ${TARGET_TOPIC:output-topic}
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      dbCircuit:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10
        minimum-number-of-calls: 5

# Logging
logging:
  level:
    com.orchestrator.adapter: INFO
    org.springframework.kafka: WARN